# Generated by Django 5.2.14 on 2026-06-28 13:03

import django.db.models.deletion
import referral_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_account', '0005_alter_clinicphysio_clinic_alter_clinicphysio_physio'),
        ('personal_account', '0005_addpatient_qr_code_addpatient_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(editable=False, max_length=14, unique=True)),
                ('referrer_name', models.CharField(max_length=100)),
                ('referrer_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('physio', 'Physiotherapist'), ('other', 'Other')], max_length=20)),
                ('referrer_contact', models.CharField(blank=True, max_length=20)),
                ('referrer_organization', models.CharField(blank=True, max_length=150)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_contact', models.CharField(blank=True, max_length=20)),
                ('patient_diagnosis', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=referral_app.models.get_nepal_time)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='personal_account.addpatient')),
                ('referred_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to=settings.AUTH_USER_MODEL)),
                ('referred_to_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clinic_account.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
