# Generated by Django 5.2.14 on 2026-06-28 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_contact',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_organization',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_type',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
