# Generated by Django 5.2.14 on 2026-06-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='follow_up_instructions',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='next_session',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='post_pain',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='post_remarks',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='pre_bp',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='pre_hr',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='pre_pain',
        ),
        migrations.RemoveField(
            model_name='treatmentsession',
            name='progress_status',
        ),
    ]
