# Generated by Django 5.2.14 on 2026-06-04 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_region_name', models.CharField(max_length=100)),
                ('region_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.region', verbose_name='Region')),
            ],
        ),
    ]
