# Generated by Django 5.2.14 on 2026-06-04 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=100)),
                ('difficulty_level', models.IntegerField(help_text='1-5')),
                ('default_sets', models.IntegerField()),
                ('default_reps', models.IntegerField()),
                ('hold_time_sec', models.IntegerField()),
                ('exercise_description', models.CharField(max_length=500)),
                ('sub_region_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.subregion', verbose_name='SubRegion')),
            ],
        ),
    ]
