# Generated by Django 5.2.14 on 2026-06-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0003_exercisemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemain',
            name='exercise_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
