# Generated by Django 5.2.14 on 2026-06-04 05:52

from django.db import migrations

def insert_regions(apps, schema_editor):
    Region = apps.get_model('exercise_app', 'Region')
    region_data = ["Head_and_Neck", "Spine", "Upper Limb", "Lower Limb", "Chest"]
    for region_name in region_data:
        Region.objects.get_or_create(region_name=region_name)

def reverse_regions(apps, schema_editor):
    Region = apps.get_model('exercise_app', 'Region')
    Region.objects.filter(region_name__in=["Head_and_Neck", "Spine", "Upper Limb", "Lower Limb", "Chest"]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('exercise_app', '0004_exercisemain_exercise_url'),
    ]
    operations = [
        migrations.RunPython(insert_regions, reverse_regions),
    ]