# Generated by Django 5.2.14 on 2026-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0006_insert_subregions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemain',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('super', 'Super Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercisemain',
            name='exercise_type',
            field=models.CharField(choices=[('isometric', 'Isometric'), ('stretching', 'Stretching'), ('strengthening', 'Strengthening'), ('rom', 'ROM'), ('mobility', 'Mobility'), ('postural', 'Postural'), ('stability', 'Stability'), ('functional', 'Functional'), ('mckenzie', 'McKenzie'), ('posture_correction', 'Posture Correction'), ('neurodynamic', 'Neurodynamic'), ('relaxation', 'Relaxation'), ('balance', 'Balance'), ('coordination', 'Coordination'), ('postural_control', 'Postural Control'), ('pnf', 'PNF'), ('neglect_training', 'Neglect Training'), ('gait_training', 'Gait Training'), ('mirror_therapy', 'Mirror Therapy'), ('motor_relearning', 'Motor Relearning'), ('tone_management', 'Tone Management'), ('cognitive_motor', 'Cognitive Motor'), ('aquatic', 'Aquatic / Hydrotherapy'), ('bfr', 'Blood Flow Restriction (BFR)'), ('suspension', 'Suspension Therapy')], max_length=50),
        ),
    ]
