# Generated by Django 5.2.14 on 2026-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0007_alter_exercisemain_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemain',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Super Level')]),
        ),
    ]
