# Generated by Django 5.2.14 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0009_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id_in_library', models.IntegerField(db_index=True, help_text='ID from the original exercise library in ')),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('hold_time_sec', models.IntegerField(default=0, help_text='Hold time in seconds for isometric exercises')),
                ('rest_time_sec', models.IntegerField(default=60, help_text='Rest time between sets in seconds')),
                ('exercise_notes', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order of exercises')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, help_text='Reference to the original exercise from ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_exercises', to='exercise_app.exercisemain')),
                ('prescription', models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise_app.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Exercise',
                'verbose_name_plural': 'Prescription Exercises',
                'db_table': 'prescription_exercises',
                'ordering': ['order', 'id'],
                'unique_together': {('prescription', 'exercise_id_in_library', 'order')},
            },
        ),
    ]
