# Generated by Django 5.2.14 on 2026-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0010_prescriptionexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionexercise',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Super Level')], default=1),
        ),
    ]
