# Generated by Django 5.2.14 on 2026-06-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0011_alter_prescriptionexercise_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='exercise_notes',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='hold_time_sec',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='rest_time_sec',
        ),
        migrations.RemoveField(
            model_name='prescriptionexercise',
            name='sets',
        ),
    ]
