# Generated by Django 5.2.14 on 2026-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0012_remove_prescription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemain',
            name='default_rest_time_sec',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='hold_time_sec',
            field=models.IntegerField(default=0, help_text='Hold time in seconds for isometric exercises'),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='rest_time_sec',
            field=models.IntegerField(default=60, help_text='Rest time between sets in seconds'),
        ),
        migrations.AddField(
            model_name='prescriptionexercise',
            name='sets',
            field=models.IntegerField(default=3),
        ),
    ]
