# Generated by Django 5.2.14 on 2026-06-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0013_exercisemain_default_rest_time_sec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard'), ('painful', 'Painful'), ('increased_symptom', 'Increased Symptom')], max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_logs', to='exercise_app.prescriptionexercise')),
            ],
            options={
                'db_table': 'exercise_feedback',
                'ordering': ['-logged_at'],
            },
        ),
    ]
