# Generated by Django 5.2.14 on 2026-05-29 05:51

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='created_at',
            field=models.DateTimeField(default=personal_account.models.get_nepal_time),
        ),
    ]
