# Generated by Django 5.2.14 on 2026-06-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0005_alter_clinicphysio_clinic_alter_clinicphysio_physio'),
        ('personal_account', '0002_addpatient_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='origin_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_assigned', to='clinic_account.clinic'),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
