# Generated by Django 5.2.14 on 2026-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal Account User'), ('clinic', 'Clinic User'), ('enterprise', 'Enterprise User')], default='personal', max_length=10),
        ),
    ]
