# Generated by Django 5.2.14 on 2026-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
