# Generated by Django 5.2.14 on 2026-05-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(default='temporary', max_length=20),
        ),
    ]
