# Generated by Django 5.2.14 on 2026-05-30 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPhysio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_physios', to='clinic_account.clinic')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clinic', 'physio')},
            },
        ),
    ]
