# Generated by Django 5.2.14 on 2026-05-31 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0002_clinicphysio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicphysio',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_user_code', to='clinic_account.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicphysio',
            name='physio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_user_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
