# Generated by Django 5.2.14 on 2026-06-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_account', '0003_alter_clinicphysio_clinic_alter_clinicphysio_physio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicphysio',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_id', to='clinic_account.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicphysio',
            name='physio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
